---
version: '3'

services:
  syncer:
    build: .
    environment:
    - GIT_REPO=https://github.com/tbouska/mkdocs-zettelkasten.git
    - GIT_BRANCH=main
    - UPDATE_INTERVAL=60
    volumes:
    - ./config/syncer:/app/config
    - site:/app/site
  nginx:
    image: nginx:1.21.4
    ports:
    - 8000:80
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - site:/site
    depends_on:
    - mkdocs
volumes:
  site:
